name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install `poetry` 
        run: |
          pipx install poetry
          poetry --version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install package
        run: |
          pip install black poetry "black[jupyter]"
      - name: Run linter
        run: |
          poetry run black .
      # - name: Run tests
      #   run: |
      #     poetry run pytest
